version: '3.8'
services:
  dev-db:
    image: postgres:14-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aqib
      POSTGRES_DB: nest
    networks:
      - database

networks:
  database: